import { PROJECTS_EN, PROJECT_ORDER_EN } from "./projects-data.en.mjs";

function caseStudy(slug) {
  const p = PROJECTS_EN[slug];
  return {
    slug: `case-study-${slug}`,
    type: "case-study",
    projectSlug: slug,
    title: `${p.name} Case Study: ${p.badge}`,
    description: `How Openappo built a ${p.badge.toLowerCase()} for ${p.name} — the challenge, the solution, and the results after launch.`,
    category: "Case Study",
    tags: [p.industry, "Case Study", "Openappo", p.name],
    date: "2026-09-26",
    readTime: "5 min read",
    excerpt: p.challenge.slice(0, 150) + "…",
    content: [
      { type: "h2", text: "About the project" },
      { type: "p", text: `${p.name} operates in ${p.industry}. Openappo built them a ${p.badge.toLowerCase()} as a fully integrated cloud system.` },
      { type: "h2", text: "The challenge" },
      { type: "p", text: p.challenge },
      { type: "h2", text: "The Openappo solution" },
      { type: "p", text: p.solution },
      { type: "ul", items: p.pills },
      { type: "h2", text: "Key dashboard indicators" },
      { type: "ul", items: p.kpis.map((k) => `${k.label}: ${k.val} (${k.trend})`) },
      { type: "h2", text: "A snapshot of the daily activity log" },
      { type: "ul", items: p.activities },
      { type: "h2", text: "Takeaway" },
      {
        type: "p",
        text: `${p.name}'s system shows what a purpose-built platform — not a generic off-the-shelf tool — can do to close real operational gaps. If your business is in ${p.industry} or a related field and you're facing similar challenges, you can see more of this project on our Portfolio page.`,
      },
    ],
  };
}

const CASE_STUDIES_EN = PROJECT_ORDER_EN.map(caseStudy);

const ARTICLES_EN = [
  {
    slug: "5-signs-your-business-needs-erp",
    type: "article",
    title: "5 Signs Your Business Needs an ERP System Now",
    description:
      "How do you know your business has outgrown spreadsheets and notebooks and needs a full ERP system? Five practical signs you can spot yourself.",
    category: "ERP Guide",
    tags: ["ERP", "Business Management", "Guide"],
    date: "2026-09-20",
    readTime: "6 min read",
    excerpt: "If you find yourself pulling sales and inventory numbers from several different spreadsheets every month, that's sign number one.",
    content: [
      { type: "p", text: "Every business starts small and runs on spreadsheets and notebooks — that's perfectly normal. The problem isn't the starting point; it's staying on those same tools long after tracking things by hand becomes nearly impossible. Here are five signs it's time to move to an integrated ERP system." },
      { type: "h2", text: "1. Your numbers live in multiple disconnected places" },
      { type: "p", text: "If sales figures sit in one file, inventory in another, and customer balances in a notebook — and every month you spend hours stitching them together — that's time you're losing on something that should update live from a single screen." },
      { type: "h2", text: "2. You don't actually know your real stock level right now" },
      { type: "p", text: "If you have to call the warehouse or walk over and check before confirming a sale to a customer, your current system (or lack of one) is making you work on guesses instead of data." },
      { type: "h2", text: "3. You have multiple branches or distribution lines, each with its own books" },
      { type: "p", text: "Multiple branches without a unified system turn into separate islands, each closing its own accounts, while management spends a long time assembling a full picture of the company's overall performance." },
      { type: "h2", text: "4. Product or service cost is calculated after the fact, not during" },
      { type: "p", text: "If you find out you lost money on a production order or a project after it's done — not while you're running it — that means no system is tracking real cost as it happens." },
      { type: "h2", text: "5. Decisions are made on gut feeling, not on a report" },
      { type: "p", text: "The most telling sign of all: the owner decides to expand or drop a product based on instinct, not real numbers in front of them. An ERP system gives you live reports you can act on in the moment." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "If you recognize two or more of these signs, it's time to think about an integrated system built around exactly how your business works — not a generic off-the-shelf tool you're forcing your operations to fit." },
    ],
  },
  {
    slug: "erp-vs-accounting-software",
    type: "article",
    title: "ERP vs. Accounting Software: What's the Real Difference?",
    description:
      "Accounting software records entries; ERP runs the whole business. Learn the practical difference and when you need each one.",
    category: "ERP Guide",
    tags: ["ERP", "Accounting", "Comparison"],
    date: "2026-09-19",
    readTime: "5 min read",
    excerpt: "Accounting software answers \"how much did we spend and earn?\" ERP answers \"why, and how do we earn more?\"",
    content: [
      { type: "p", text: "Many business owners ask: \"I already have accounting software, why do I need an ERP?\" It's a fair question, but the two tools solve different problems." },
      { type: "h2", text: "Accounting software: recording what happened" },
      { type: "p", text: "Standard accounting software focuses on journal entries, invoices, and the balance sheet. It's a documentation and financial-reporting tool — it tells you how much came in, how much went out, and every account's balance." },
      { type: "h2", text: "ERP: managing what's happening, live" },
      { type: "p", text: "An ERP system links accounting to every other activity in the business: inventory, sales, purchasing, manufacturing, sales reps, HR. When a sale happens, the invoice is recorded, stock drops, and the customer's balance updates — all in one connected transaction." },
      { type: "h2", text: "A concrete example" },
      { type: "p", text: "In plain accounting software: a rep makes a sale, then someone has to manually enter the stock movement, then someone else compiles a rep-performance report at month end. In ERP: all of that happens automatically from the same invoice." },
      { type: "h2", text: "When accounting software is enough" },
      { type: "p", text: "If your operation is simple (a small service business, no complex inventory or multiple branches), good accounting software can cover you for a while." },
      { type: "h2", text: "When you need ERP" },
      { type: "p", text: "Once you have inventory, branches, sales reps, and manufacturing — any business where more than one department affects the others — that's when ERP saves time and accuracy that accounting software alone was never built to provide." },
    ],
  },
  {
    slug: "choosing-inventory-management-system",
    type: "article",
    title: "How to Choose an Inventory Management System for Your Business",
    description:
      "A practical guide to choosing the right inventory system: barcode tracking, periodic counts, item aging, and storage cost.",
    category: "ERP Guide",
    tags: ["Inventory Management", "Stock Control", "Guide"],
    date: "2026-09-18",
    readTime: "6 min read",
    excerpt: "The right inventory system doesn't just \"count units\" — it tells you the right call: buy now or wait?",
    content: [
      { type: "p", text: "Inventory is usually a business's largest cash investment, and any mistake in it — a sudden shortage or excess buildup — costs real money. Choosing the right inventory system starts with understanding your actual needs, not a features checklist." },
      { type: "h2", text: "1. Barcode or serial-level tracking" },
      { type: "p", text: "If you deal with large item counts or devices with individual serial numbers, the system needs barcode or serial tracking — manual eyeball counting won't keep up at that scale." },
      { type: "h2", text: "2. Multiple warehouses or branches" },
      { type: "p", text: "The system should show each item's balance per warehouse separately, and let you transfer stock between warehouses with a clear log for every transfer." },
      { type: "h2", text: "3. Reorder thresholds and alerts" },
      { type: "p", text: "The best system warns you before an item runs out, not after a customer asks for it and you discover the shortage." },
      { type: "h2", text: "4. Linking inventory to sales and manufacturing" },
      { type: "p", text: "If you have a production line, inventory needs to connect to work orders so raw-material consumption and finished goods update automatically — not through a manual reconciliation at the end of the week." },
      { type: "h2", text: "5. Item movement reports over time" },
      { type: "p", text: "Not every item moves at the same speed. A good system shows you which items are stagnant and which sell fast, so your purchasing decisions are based on actual data." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "Before choosing an inventory system, list your top three current inventory problems, and check whether the solution in front of you actually solves them — or just counts units." },
    ],
  },
  {
    slug: "cloud-erp-multi-branch",
    type: "article",
    title: "Why Cloud Systems Matter for Managing Multiple Branches",
    description:
      "Managing several branches from one place is now possible thanks to cloud systems. How does it work, and why is it better than a local system per branch?",
    category: "ERP Guide",
    tags: ["Cloud", "Multi-Branch", "ERP"],
    date: "2026-09-17",
    readTime: "5 min read",
    excerpt: "A local system per branch means disconnected data. A cloud system means the whole company runs on one shared database.",
    content: [
      { type: "p", text: "When a company opens a new branch, the first technical question is: install a separate system in each branch, or run everyone on one shared cloud system? That choice shapes the company's future." },
      { type: "h2", text: "Local systems per branch: locked-in data" },
      { type: "p", text: "If every branch runs its own system, senior management won't know the company's overall performance without manually collecting reports from each branch — which takes time and reduces decision accuracy." },
      { type: "h2", text: "Cloud systems: one database, layered permissions" },
      { type: "p", text: "In a cloud system, every branch logs its activity into the same database, and management can see each branch's performance live from anywhere, with permissions that can restrict one branch from seeing another's data when needed." },
      { type: "h2", text: "Example: transferring stock between two branches" },
      { type: "p", text: "In a separate local setup, transferring stock between branches means a paper slip and manual entry on both ends. In a unified cloud system, the transfer is recorded once and appears instantly in both branches' balances." },
      { type: "h2", text: "Security and backups" },
      { type: "p", text: "A local system means that if a branch's machine fails, you could lose that branch's entire data. A cloud system keeps automatic backups independent of any single branch's hardware failure." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "For any company planning to expand into new branches, a cloud system isn't a luxury — it's the foundation that keeps growth manageable instead of chaotic." },
    ],
  },
  {
    slug: "pos-system-guide",
    type: "article",
    title: "The Complete Guide to Point-of-Sale (POS) Systems for Shop and Showroom Owners",
    description:
      "Everything you need to know before choosing a POS system: checkout speed, shift management, and inventory integration.",
    category: "ERP Guide",
    tags: ["POS", "Point of Sale", "Guide"],
    date: "2026-09-16",
    readTime: "6 min read",
    excerpt: "The right POS system isn't just a screen that prints a receipt — it's the one that closes shifts correctly and updates inventory at the same instant.",
    content: [
      { type: "p", text: "A point-of-sale (POS) system is the direct touchpoint between your business and your customer, so any slowness or error is felt immediately. Choosing it well saves time in the queue and accuracy in your books." },
      { type: "h2", text: "Speed matters more than any other feature" },
      { type: "p", text: "The first thing to test in any POS system: how many seconds does a sale take from scanning the item to printing the receipt? The difference between 3 seconds and 10 seconds compounds fast in a busy queue." },
      { type: "h2", text: "Shift management and accounting" },
      { type: "p", text: "Every shift needs to close with a clear balance: how much cash, how much by card, how much through e-wallets — and any discrepancy should be logged against the responsible employee, not lost in the rush." },
      { type: "h2", text: "Direct inventory integration" },
      { type: "p", text: "Every sale needs to deduct from inventory instantly. If the POS system is disconnected from inventory, you'll discover a shortage only after selling an item to a second customer that isn't actually there." },
      { type: "h2", text: "Support for multiple payment methods" },
      { type: "p", text: "Cash, card, e-wallets, and sometimes deferred payment for certain customers — the system needs to record all of them with the same precision in one report." },
      { type: "h2", text: "Reporting for multi-branch owners" },
      { type: "p", text: "If you have more than one branch, you need to easily compare each branch's performance: best-selling item, top-performing staff member, and peak sales hours." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "A good POS system disappears into the background — customers and staff feel that checkout is fast and smooth, and management finds every number they need already there, without having to ask anyone." },
    ],
  },
  {
    slug: "sales-reps-route-management",
    type: "article",
    title: "How to Manage Distribution Reps and Delivery Routes Professionally",
    description:
      "Managing sales reps isn't just \"who's going where\" — it's stock custody, cash collection, and performance evaluation. How does a business system tie it all together?",
    category: "ERP Guide",
    tags: ["Distribution", "Sales Reps", "Routes"],
    date: "2026-09-15",
    readTime: "5 min read",
    excerpt: "Every delivery rep is effectively a \"mobile branch\" — carrying stock and collecting cash — and needs to be tracked with the same rigor as a fixed branch.",
    content: [
      { type: "p", text: "Distribution companies depend entirely on their reps, yet many still manage them with a paper ledger and phone calls. The problem is that every rep represents a real financial risk without precise tracking." },
      { type: "h2", text: "Custody: goods and cash" },
      { type: "p", text: "Every rep takes stock on their own account in the morning and returns at day's end with the remaining stock and cash collected. Without a system, reconciling that custody takes time and can hide errors or manipulation that's hard to catch." },
      { type: "h2", text: "Routes: coverage instead of guesswork" },
      { type: "p", text: "Assigning customers to fixed routes ensures every customer is visited regularly, and makes it easy to measure each route's performance: sales, collections, and how much of the assigned customer list it actually covers." },
      { type: "h2", text: "Collections tied directly to the customer account" },
      { type: "p", text: "Any collection from a rep needs to post to the customer's account immediately, not days later — so management knows every customer's real balance at any time." },
      { type: "h2", text: "Measuring each rep's performance" },
      { type: "p", text: "A good rep-management system gives you a clear report: who's the top seller, who collects fastest, and who needs more oversight — data you can act on, not just an impression." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "Professional rep management isn't administrative overhead — it's direct protection for the company's cash and its mobile inventory." },
    ],
  },
  {
    slug: "e-invoice-egypt-guide",
    type: "article",
    title: "E-Invoicing in Egypt: Your Complete Guide",
    description:
      "Egypt's e-invoicing system is now mandatory for a large share of businesses. How does an ERP system make compliance effortless?",
    category: "ERP Guide",
    tags: ["E-Invoicing", "Egypt", "Tax Compliance"],
    date: "2026-09-14",
    readTime: "5 min read",
    excerpt: "E-invoicing isn't just a tax requirement — done right, it saves time on every single invoice you issue.",
    content: [
      { type: "p", text: "The e-invoicing system overseen by the Egyptian Tax Authority is now a core part of running any registered business. Companies still issuing invoices manually, or from a disconnected system, carry an extra burden every day." },
      { type: "h2", text: "What's wrong with manual issuance?" },
      { type: "p", text: "Issuing an e-invoice manually means entering the same invoice data twice: once in the sales system, once in the e-invoicing portal. That's wasted time and a real risk of mismatches between the two copies." },
      { type: "h2", text: "The fix: a direct link from your sales system" },
      { type: "p", text: "An integrated ERP system issues the e-invoice automatically the instant a sale is recorded, so there's no double entry and no gap between the customer's copy and the officially registered one." },
      { type: "h2", text: "Archiving and status tracking" },
      { type: "p", text: "Every e-invoice carries a status (accepted, rejected, pending), and a good system tracks those statuses and flags which invoice needs correction — instead of you discovering it months later." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "E-invoicing compliance is far easier once it's a natural part of the sale itself, not a separate extra step after every transaction." },
    ],
  },
  {
    slug: "manufacturing-cost-calculation",
    type: "article",
    title: "How an ERP System Calculates Manufacturing Cost Accurately",
    description:
      "Material + labor + overhead = product cost. Calculating it manually is slow and error-prone. How does an ERP system get it right, in real time?",
    category: "ERP Guide",
    tags: ["Manufacturing", "Costing", "ERP"],
    date: "2026-09-13",
    readTime: "6 min read",
    excerpt: "If you only know a product's real cost after you've sold it, you've been pricing on a guess, not a calculation.",
    content: [
      { type: "p", text: "Any manufactured product's real cost is built from three elements: the materials used, the labor that ran it, and overhead (electricity, maintenance, machine depreciation). Calculating these manually after a product is finished leaves pricing based on estimation, not fact." },
      { type: "h2", text: "1. Material cost: more than just the purchase price" },
      { type: "p", text: "An ERP system tracks exactly which materials were issued to which production order, at the actual price at the time of issue — not an average — so cost stays accurate even if material prices shift between shipments." },
      { type: "h2", text: "2. Labor cost by production stage" },
      { type: "p", text: "If a product passes through several production stages, the system allocates labor cost to each stage separately, so you know exactly which stage is the most expensive and can work on improving it." },
      { type: "h2", text: "3. Overhead and indirect expenses" },
      { type: "p", text: "Costs like electricity and maintenance aren't tied to one specific order, but a good system allocates them across products with a clear formula (by run hours or quantity) instead of ignoring them entirely." },
      { type: "h2", text: "4. Actual cost vs. estimated cost" },
      { type: "p", text: "The biggest benefit: you can compare the cost you expected before production against the actual cost after, and know exactly where the difference came from — a material price change, longer run time, or higher waste than planned." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "Accurate pricing starts with accurate cost. An ERP system gives you the real number as it happens, not an estimate you correct every time you lose money on a production order." },
    ],
  },
  {
    slug: "digital-management-ngos",
    type: "article",
    title: "Digital Transformation for Charities and Non-Profit Organizations",
    description:
      "Transparency in spending is a charity's most important asset. How does a digital system document every case and every pound, and build donor trust?",
    category: "ERP Guide",
    tags: ["Charities", "Non-Profit", "Transparency"],
    date: "2026-09-12",
    readTime: "5 min read",
    excerpt: "A donor doesn't just want to give — they want to see exactly where their money went.",
    content: [
      { type: "p", text: "Charities and non-profits run on donor trust, and that trust is built through full transparency in every disbursement. Paper-based or spreadsheet management turns that documentation into a massive, error-prone manual effort." },
      { type: "h2", text: "Documenting every case individually" },
      { type: "p", text: "A good digital system ties every disbursement to a specific case (a family, a patient, an orphan, a project), so any internal or external auditor can trace every pound donated to exactly how it was spent." },
      { type: "h2", text: "A portal for beneficiaries and guardians" },
      { type: "p", text: "In cases like nurseries or sponsorships, a dedicated portal for guardians cuts down the number of calls and questions, giving direct reassurance instead of waiting on a monthly report." },
      { type: "h2", text: "Reports ready for oversight bodies" },
      { type: "p", text: "Charities face periodic reviews from regulators and donors. A system that generates spending and donation reports automatically saves weeks of manual preparation at review time." },
      { type: "h2", text: "Efficient case triage and classification" },
      { type: "p", text: "With hundreds of cases, manual triage is slow and sometimes unfair. A digital system classifies cases by priority and type, making resource distribution faster and more equitable." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "Digital transformation for charities isn't a technical luxury — it's the tool that turns transparency from a slogan into a documented, everyday practice." },
    ],
  },
  {
    slug: "why-erp-projects-fail",
    type: "article",
    title: "Why ERP Projects Fail — And How to Avoid It",
    description:
      "Not every ERP rollout succeeds the first time. The most common reasons for failure, and how a system built around how you actually work avoids them.",
    category: "ERP Guide",
    tags: ["ERP", "Implementation", "Common Mistakes"],
    date: "2026-09-11",
    readTime: "6 min read",
    excerpt: "The biggest reason ERP projects fail isn't technical — it's that the business was forced to change how it works to fit an off-the-shelf tool.",
    content: [
      { type: "p", text: "Plenty of companies try to roll out an ERP system and end up abandoning it after a while — not because the idea was wrong, but for recurring reasons you can avoid from the start." },
      { type: "h2", text: "1. A generic off-the-shelf system instead of a tailored solution" },
      { type: "p", text: "Generic software is built to fit as many businesses as possible, which means it forces its own way of working onto you. The result: employees find workarounds (a parallel spreadsheet), and the system quietly falls out of use." },
      { type: "h2", text: "2. No real employee training" },
      { type: "p", text: "A powerful system in the hands of an untrained employee is worthless. Training needs to cover their actual day-to-day scenarios, not a generic feature tour." },
      { type: "h2", text: "3. Rolling out everything at once" },
      { type: "p", text: "Trying to move every department onto the new system on the same day multiplies risk. A phased rollout — one department goes live and stabilizes, then the next joins — is far safer." },
      { type: "h2", text: "4. No ongoing support after delivery" },
      { type: "p", text: "Any system needs adjustments once it's actually in use — a missing screen, a report that needs tweaking. If support stops after delivery, the system's usefulness fades over time." },
      { type: "h2", text: "5. Not involving employees in the design from day one" },
      { type: "p", text: "The employees who'll use the system daily hold important practical details. Ignoring their input during design leads to a technically sound but impractical system." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "The systems that succeed are the ones designed around how the company actually works, backed by real training, a phased rollout, and ongoing support — not an off-the-shelf tool you're forcing your business to fit." },
    ],
  },
];

export const POSTS_EN = [...CASE_STUDIES_EN, ...ARTICLES_EN];

export function getPostBySlugEn(slug) {
  return POSTS_EN.find((p) => p.slug === slug) || null;
}

export function getAllSlugsEn() {
  return POSTS_EN.map((p) => p.slug);
}
