"use client";

import { useEffect, useRef, useState } from "react";
import ContactWidget from "./ContactWidget";

const FRAME_COUNT = 60;

export default function ScrollSequence() {
  const canvasRef = useRef(null);
  const trackRef = useRef(null);
  const heroRef = useRef(null);
  const bottomBarRef = useRef(null);
  const contactWidgetRef = useRef(null);
  const scrollHintRef = useRef(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    const track = trackRef.current;
    const hero = heroRef.current;
    const bottomBar = bottomBarRef.current;
    const contactWidget = contactWidgetRef.current;
    const scrollHint = scrollHintRef.current;
    const ctx = canvas.getContext("2d", { alpha: false });

    // The canvas paints its own backdrop, so it has to know the theme; a black
    // letterbox on a light page looks like a broken image.
    const isLight = () => document.documentElement.dataset.pfTheme === "light";

    // Under reduced-motion, map frames 1:1 to scroll position with no eased catch-up
    const ease = window.matchMedia("(prefers-reduced-motion: reduce)").matches
      ? 1
      : 0.12;

    const cssWidth =
      window.innerWidth || document.documentElement.clientWidth || 1280;

    // Probe images are generated by our own encoder (scripts/build-frames.mjs
    // era) — a hand-copied AVIF probe decoded nowhere and silently sent every
    // browser to the fallback format. Both are 2x2, so a browser that "loads"
    // a broken image with naturalWidth 0 still counts as unsupported.
    const PROBES = {
      avif:
        "data:image/avif;base64,AAAAHGZ0eXBhdmlmAAAAAG1pZjFhdmlmbWlhZgAAANZtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAAAAAAACJpbG9jAAAAAERAAAEAAQAAAAAA+gABAAAAAAAAABoAAAAjaWluZgAAAAAAAQAAABVpbmZlAgAAAAABAABhdjAxAAAAAA5waXRtAAAAAAABAAAAVmlwcnAAAAA4aXBjbwAAAAxhdjFDgSACAAAAABRpc3BlAAAAAAAAAAIAAAACAAAAEHBpeGkAAAAAAwgICAAAABZpcG1hAAAAAAAAAAEAAQOBAgMAAAAibWRhdBIACgc4ADaQENBpMg0dgmLE4AAWAASQNZaA",
      webp: "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAABQAQCdASoCAAIABUB8JaQABHQAAAAAAAA=",
    };

    const canDecode = (src) =>
      new Promise((res) => {
        const im = new Image();
        im.onload = () => res(im.naturalWidth === 2);
        im.onerror = () => res(false);
        im.src = src;
      });

    // Never send more pixels than the viewport can physically paint: the canvas
    // renders at cssWidth x dpr (dpr capped at 2), so a 393px phone shows 786px.
    const frameSet = cssWidth <= 500 ? "1280" : "1920";
    const pad = (i) => String(i + 1).padStart(3, "0");

    // Master JPEGs until the probes resolve; swapped before any frame loads.
    let framePath = (i) => `/frames/frame-${pad(i)}.jpg`;

    const isPhone = cssWidth < 768;
    const pxPerFrame = isPhone ? 70 : 105;
    track.style.height = `${FRAME_COUNT * pxPerFrame}px`;

    const images = new Array(FRAME_COUNT);
    let imgW = 1280;
    let imgH = 720;

    let currentFrame = 0;
    let targetFrame = 0;
    let lastDrawn = -1;
    let rafId = 0;
    let vw = 0;
    let vh = 0;

    const setCanvasSize = () => {
      vw = window.innerWidth;
      vh = window.innerHeight;
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.round(vw * dpr);
      canvas.height = Math.round(vh * dpr);
      canvas.style.width = vw + "px";
      canvas.style.height = vh + "px";
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      lastDrawn = -1;
    };

    const isReady = (i) => {
      const im = images[i];
      return !!im && im.complete && im.naturalWidth > 0;
    };

    // Frames arrive out of order over the network. Never leave the canvas
    // blank waiting for one — fall back to the closest frame we already have.
    const nearestReady = (index) => {
      if (isReady(index)) return index;
      for (let d = 1; d < FRAME_COUNT; d++) {
        if (index - d >= 0 && isReady(index - d)) return index - d;
        if (index + d < FRAME_COUNT && isReady(index + d)) return index + d;
      }
      return -1;
    };

    const drawFrame = (index) => {
      const img = images[index];
      if (!img || !img.complete || img.naturalWidth === 0) return;
      const contain = vh > vw;

      if (contain) {
        // Soft ambient background
        const bgScale = Math.max(vw / imgW, vh / imgH) * 1.15;
        const bw = imgW * bgScale;
        const bh = imgH * bgScale;
        ctx.save();
        ctx.filter = isLight() ? "blur(28px) brightness(1.25)" : "blur(28px) brightness(0.4)";
        ctx.drawImage(img, (vw - bw) / 2, (vh - bh) / 2, bw, bh);
        ctx.restore();

        // Pin video frame cleanly at the upper section of phone screen
        // Flush to the top on phones — the 56px strip above was dead space.
        const topOffset = 0;
        const scale = vw / imgW;
        const w = vw;
        const h = Math.round(imgH * scale);
        ctx.drawImage(img, 0, topOffset, w, h);

        // Soft gradient fade at bottom of video frame for smooth transition
        ctx.save();
        const grad = ctx.createLinearGradient(0, topOffset + h - 24, 0, topOffset + h);
        grad.addColorStop(0, "rgba(0,0,0,0)");
        grad.addColorStop(1, isLight() ? "rgba(242,245,248,0.9)" : "rgba(0,0,0,0.85)");
        ctx.fillStyle = grad;
        ctx.fillRect(0, topOffset + h - 24, w, 24);
        ctx.restore();
      } else {
        const scale = Math.max(vw / imgW, vh / imgH);
        const w = imgW * scale;
        const h = imgH * scale;
        ctx.drawImage(img, (vw - w) / 2, (vh - h) / 2, w, h);
      }
      lastDrawn = index;
    };

    const computeTarget = () => {
      const total = track.offsetHeight - window.innerHeight;
      const progress =
        total > 0 ? Math.min(Math.max(window.scrollY / total, 0), 1) : 0;
      targetFrame = progress * (FRAME_COUNT - 1);
    };

    const tick = () => {
      currentFrame += (targetFrame - currentFrame) * ease;
      if (Math.abs(targetFrame - currentFrame) < 0.001) currentFrame = targetFrame;
      // Redraw whenever the best frame we can show changes — that covers both
      // scrolling and a nearer frame finishing its download.
      const resolved = nearestReady(Math.round(currentFrame));
      if (resolved >= 0 && resolved !== lastDrawn) drawFrame(resolved);

      // Progressive entrance tied to scroll position:
      // - Hero card appears between 50% and 75% scroll
      // - Action buttons bar appears from 80% scroll onwards
      const progress = currentFrame / (FRAME_COUNT - 1);
      const heroProgress = Math.min(Math.max((progress - 0.50) / 0.25, 0), 1);
      const barProgress = Math.min(Math.max((progress - 0.80) / 0.18, 0), 1);
      const hintProgress = Math.max(1 - progress / 0.35, 0);


      if (hero) {
        hero.style.opacity = heroProgress.toFixed(3);
        if (vw < 768) {
          hero.style.transform = `translateY(${(20 * (1 - heroProgress)).toFixed(1)}px)`;
        } else {
          hero.style.transform = `translateY(${(32 * (1 - heroProgress)).toFixed(1)}px)`;
        }
        hero.style.pointerEvents = heroProgress > 0.4 ? "auto" : "none";
      }

      if (bottomBar) {
        bottomBar.style.opacity = barProgress.toFixed(3);
        // Vertical rise only. The dock is a flex row/column that already places
        // these; a leftover translateX(-50%) from the old left:50% positioning
        // shifted the bar ~185px off its slot, which is what made the gaps
        // uneven and dropped it on top of the trust badge.
        bottomBar.style.transform = `translateY(${(20 * (1 - barProgress)).toFixed(1)}px)`;
        bottomBar.style.pointerEvents = barProgress > 0.4 ? "auto" : "none";
      }

      if (contactWidget) {
        contactWidget.style.opacity = barProgress.toFixed(3);
        contactWidget.style.transform = `translateY(${(20 * (1 - barProgress)).toFixed(1)}px)`;
        contactWidget.style.pointerEvents = barProgress > 0.4 ? "auto" : "none";
      }

      if (scrollHint) {
        scrollHint.style.opacity = hintProgress.toFixed(3);
        scrollHint.style.pointerEvents = hintProgress > 0.2 ? "auto" : "none";
      }

      rafId = requestAnimationFrame(tick);
    };

    const onScroll = () => computeTarget();

    let lastW = window.innerWidth;
    let lastH = window.innerHeight;
    let resizeTimer = 0;
    const onResize = () => {
      const w = window.innerWidth;
      const h = window.innerHeight;
      // Height-only changes used to be ignored outright, which is wrong on
      // phones: the first scroll hides the browser's URL bar and the viewport
      // grows (measured 720 -> 844), while the canvas kept its old height. The
      // picture then sat 124px short of the bottom and read as the whole screen
      // lifting away. Small jitter is still ignored — the bar animates, and
      // resizing the canvas on every pixel of that would thrash.
      if (w === lastW && Math.abs(h - lastH) < 40) return;
      clearTimeout(resizeTimer);
      resizeTimer = setTimeout(() => {
        lastW = window.innerWidth;
        lastH = window.innerHeight;
        setCanvasSize();
        computeTarget();
        const r = nearestReady(Math.round(currentFrame));
        if (r >= 0) drawFrame(r);
      }, 90);
    };

    // Load order matters far more than raw bandwidth here: firing all 60 at
    // once means the browser's connection pool delivers them roughly in order,
    // so scrolling ahead lands on frames that haven't arrived yet. Instead:
    // frame 0 first (unblocks the canvas), then a coarse pass spread across the
    // whole sequence so every scroll position has something near it, then the
    // in-between frames to sharpen it up.
    const STRIDE = 5;
    const order = [0];
    for (let i = STRIDE; i < FRAME_COUNT; i += STRIDE) order.push(i);
    for (let i = 1; i < FRAME_COUNT; i++) {
      if (i % STRIDE !== 0) order.push(i);
    }

    const startLoad = (i) =>
      new Promise((resolve) => {
        const img = new Image();
        img.decoding = "async";
        if (i === 0) img.fetchPriority = "high";
        img.onload = () => {
          if (i === 0) {
            imgW = img.naturalWidth || imgW;
            imgH = img.naturalHeight || imgH;
            setCanvasSize();
            computeTarget();
            drawFrame(0);
            canvas.style.opacity = "1";
          }
          resolve();
        };
        img.onerror = resolve; // a missing frame must not stall the queue
        img.src = framePath(i);
        images[i] = img;
      });

    let cancelled = false;
    (async () => {
      // AVIF → WebP → the master JPEGs, whichever this browser can actually decode.
      if (await canDecode(PROBES.avif)) {
        framePath = (i) => `/frames/${frameSet}/frame-${pad(i)}.avif`;
      } else if (await canDecode(PROBES.webp)) {
        framePath = (i) => `/frames/${frameSet}/frame-${pad(i)}.webp`;
      }
      if (cancelled) return;

      await startLoad(0);
      let next = 1;
      const worker = async () => {
        while (!cancelled && next < order.length) {
          await startLoad(order[next++]);
        }
      };
      await Promise.all(Array.from({ length: 6 }, worker));
    })();

    setCanvasSize();
    computeTarget();
    currentFrame = targetFrame;
    rafId = requestAnimationFrame(tick);

    // The canvas only repaints when the chosen frame changes, so a theme flip
    // would leave the old letterbox until the next scroll. Force a redraw.
    const themeWatch = new MutationObserver(() => {
      lastDrawn = -1;
    });
    themeWatch.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["data-pf-theme"],
    });

    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onResize);

    return () => {
      cancelled = true;
      clearTimeout(resizeTimer);
      themeWatch.disconnect();
      cancelAnimationFrame(rafId);
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onResize);
    };
  }, []);

  return (
    <div ref={trackRef} style={{ position: "relative", touchAction: "pan-y" }}>
      <canvas
        ref={canvasRef}
        style={{
          position: "fixed",
          inset: 0,
          width: "100%",
          height: "100%",
          display: "block",
          opacity: 0,
          transition: "opacity 0.5s ease",
          background: "var(--pf-canvas-bg, #000)",
        }}
      />

      {/* Initial Scroll Hint - Windows / Desktop Mouse Mockup */}
      <div ref={scrollHintRef} className="scroll-hint-wrapper">
        <div className="mouse-scroll-indicator" aria-label="مرّر للأسفل">
          <div className="mouse-device">
            <div className="mouse-wheel-track">
              <div className="mouse-wheel-dot" />
            </div>
            <span className="mouse-scroll-text">مرّر للأسفل</span>
            <div className="mouse-arrow-indicator">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round">
                <path d="M7 10l5 5 5-5" />
              </svg>
            </div>
          </div>
        </div>

        {/* Phone swipe mockup - phones only, restored from 588c667^ */}
      <div className="mobile-swipe-guide">
        <div className="phone-mockup-frame">
          <div className="phone-mockup-speaker" />
          <div className="phone-mockup-screen">
            <div className="swipe-trail-glow" />
            <div className="swipe-hand-wrapper">
              <svg viewBox="0 0 24 24" fill="none" className="swipe-hand-svg">
                <path
                  d="M9 11.25V4.5A1.5 1.5 0 0 1 10.5 3v0A1.5 1.5 0 0 1 12 4.5v6.75M12 9V6A1.5 1.5 0 0 1 13.5 4.5v0A1.5 1.5 0 0 1 15 6v3.75M15 9.75V7.5A1.5 1.5 0 0 1 16.5 6v0A1.5 1.5 0 0 1 18 7.5v3.75M9 11.25a2.25 2.25 0 0 0-2.25-2.25v0A2.25 2.25 0 0 0 4.5 11.25v3.75a6.75 6.75 0 0 0 6.75 6.75h.75a6.75 6.75 0 0 0 6.75-6.75v-5.25"
                  stroke="#ff7a7a"
                  strokeWidth="1.8"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </div>
            <span className="swipe-hint-text">اسحب الشاشة</span>
          </div>
          <div className="phone-mockup-homebar" />
        </div>
      </div>
      </div>

      {/* Progressive Hero Overlay & Bottom Dock Elements Wrapper */}
      <div className="bottom-dock-container">
        {/* 1. Right: Progressive Hero Overlay */}
        <div ref={heroRef} className="hero-overlay">
          <div className="hero-glass-card">
            <div className="hero-tagline">
              <span className="hero-tagline-dot" />
              <span>منظومة إدارة وتطوير الأعمال الذكية</span>
            </div>

            <div className="hero-heading-group">
              <h1 className="hero-main-title">
                <img
                  src="/brand/openappo-wordmark-dark.png"
                  alt="Openappo"
                  className="hero-title-logo"
                />
              </h1>
              <div className="hero-custom-slogan">
                <span>بنصمم السيستم حسب طريقة شغلك بالظبط</span>
                <span className="slogan-emoji">👌</span>
              </div>
            </div>

            <div className="hero-desc-container">
              <div className="hero-desc-bar" />
              <p className="hero-desc">
                ودّع فوضى الفواتير والإكسل المشتت. أدر مبيعاتك، مخزونك، وتقاريرك المالية والإدارية{" "}
                <span className="hero-desc-highlight">لحظة بلحظة وبأعلى كفاءة</span>، لاتخاذ قرارات أسرع وتنمية أرباحك بثقة.
              </p>
            </div>
          </div>
        </div>

        {/* 2. Mid-Right: Floating Action Buttons Bar */}
        <div ref={bottomBarRef} className="hero-bottom-bar">
          <a href="/how-it-works" className="btn-how-it-works">
            <span className="btn-how-icon">⚡</span>
            <span>كيف نعمل</span>
          </a>

          <div className="bottom-bar-subrow">
            <a href="/portfolio" className="btn-explore">
              <span>سابقة الأعمال</span>
              <span className="btn-arrow-icon">←</span>
            </a>

            <a href="/testimonials" className="btn-testimonials">
              <span className="btn-star-icon">★</span>
              <span>آراء العملاء</span>
            </a>
          </div>
        </div>


        {/* 4. Left: Floating Contact FAB Widget */}
        <ContactWidget innerRef={contactWidgetRef} />
      </div>
    </div>
  );
}

