export const FALLBACK_PROJECTS_AR = [
  {
    slug: "kishk",
    name: "مؤسسة أحمد كشك",
    subtitle: "منظومة إدارة تصنيع وتركيب الستائر والمفروشات الفاخرة",
    desc: "منظومة سحابية متكاملة تدير دورة العمل الكاملة لمؤسسة أحمد كشك عبر فروعها الأربعة: بدءاً من استقبال العميل ورفع المقاسات والمعاينات الميدانية بدقة (نوع المجرى، كشكشة القماش، ارتفاعات السقف)، ثم التسعير والتعاقد، مروراً بأوامر التشغيل وقص الأقمشة والتفصيل في المشغل وتركيب الإكسسوارات، وصولاً إلى التركيب النهائي في موقع العميل واعتماد التسليم. تشمل المنظومة إدارة مخزون الأثواب والقطوعات، حسابات العملاء والتحصيلات، فواتير المبيعات، وصلاحيات منفصلة لكل فرع مع تقارير تشغيلية ومالية لحظية.",
    logo: "/logos/kishk.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "mazaya",
    name: "مزايا للأثاث",
    subtitle: "نظام تخطيط موارد (ERP) لمصانع ومعارض الأثاث المودرن",
    desc: "نظام تخطيط موارد متقدم (ERP) مصمم خصيصاً لمصانع ومعارض مزايا للأثاث لربط خطوط الإنتاج والورش بالإدارة المالية في منظومة واحدة. يدير دورة أوامر التشغيل والإنتاج (غرف نوم، سفرة، صالونات، مطابخ)، وتتبع استهلاك ألواح الخشب (MDF، كونتر، زان) والإكسسوارات والمفصلات بدقة، وحساب تكلفة كل أمر تصنيع بدقة (خامات + مصنعيات + مقاولو باطن + هوالك). يشمل خزائن منفصلة للمصنع وتجارة الألواح، دفتر يومية محاسبي متكامل، ومتابعة النقل الداخلي بين المعارض والورش مع تقارير تكلفة وربحية تفصيلية.",
    logo: "/logos/mazaya.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "elnazlawy",
    name: "معرض النزلاوي",
    subtitle: "منظومة إدارة تجارة وتوزيع الأجهزة الكهربائية والإضاءة",
    desc: "منظومة شاملة لإدارة صالات العرض وشبكات التوزيع لمعرض النزلاوي للأجهزة الكهربائية والمنزلية والإضاءة. تدير مبيعات المعرض النقدية والآجلة والتقسيط، خطوط سير سيارات التوزيع المتنقلة بجرد مخزني مستقل لكل سيارة، ودورة الشيكات البنكية وحافظات التحصيل ومواعيد الاستحقاق. توفر جرد المخازن بنظام الباركود، كشوف حسابات تفصيلية للعملاء والموردين، حدود الائتمان، ومتابعة سيولة الخزائن المتعددة مع تقارير أرباح المبيعات والمديونيات لحظة بلحظة.",
    logo: "/logos/elnazlawy.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "elhoot",
    name: "الحوت للأدوات الكهربائية",
    subtitle: "نظام إدارة تجارة الجملة وشبكات توزيع الكابلات والمهمات",
    desc: "نظام متخصص في إدارة تجارة الجملة والتوزيع الواسع للمهمات والكابلات والأدوات الكهربائية. يدير دورة المبيعات والمشتريات وحركات التوريد للمشاريع وتجار التجزئة، ويتابع خطوط سير المناديب ومخازن سيارات التوزيع مع إصدار الفواتير الفورية وتحصيل الميدان. يتضمن المنظومة إدارة متقدمة لأعمار الديون والحدود الائتمانية، التحويلات بين المخازن الرئيسية والفرعية، مطابقة الخزائن وحسابات الموردين والشيكات الآجلة مع لوحات بيانية دقيقة لحركة السيولة والأرباح.",
    logo: "/logos/elhoot.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "elnesr",
    name: "النسر للتوزيع",
    subtitle: "منظومة إدارة أسطول التوزيع والمبيعات الميدانية والمناديب",
    desc: "منظومة سحابية قوية مخصصة لشركات التوزيع وأساطيل النقل، تجمع حركة المبيعات والمخازن المتنقلة وشؤون الموظفين في منصة واحدة. تتيح تتبع خطوط سير سيارات التوزيع بالمحافظات، وإدارة عهد المناديب ومبيعاتهم الميدانية والتحصيلات الفورية، مع تسوية العهد اليومية ومطابقة النقدية آلياً. تشمل إصدار الفواتير الضريبية المعتمدة، حسابات العملاء والموردين، ومؤشرات لحظية لأداء المبيعات وحركة الأصناف الراكدة والسريعة.",
    logo: "/logos/elnesr.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "rtx",
    name: "RTX للتجارة والتصنيع",
    subtitle: "نظام إدارة التصنيع الصناعي ومراحل الإنتاج المتتابعة",
    desc: "نظام صناعي متطور لإدارة ومراقبة خطوط الإنتاج عبر مراحله الثلاث المتتابعة: 1) استلام الخامات والمواد الأولية وفحص جودتها، 2) خطوط التشغيل والتصنيع والتركيب، 3) المنتج التام الجاهز للتعبئة والتوريد. يدير شجرة المنتج (BOM)، أوامر الشغل، حساب الهوالك، وتكلفة الخامات والتشغيل لكل مرحلة بدقة. يربط المصانع والموردين بالمبيعات والمدفوعات وكشوف الحسابات والخزائن في منظومة موحدة تضمن أعلى كفاءة تشغيلية وربحية.",
    logo: "/logos/rtx.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "maspero",
    name: "ماسبيرو للخدمات الرقمية",
    subtitle: "منظومة نقاط البيع (POS) وإدارة المحافظ الإلكترونية والورديات",
    desc: "منظومة سحابية متخصصة لإدارة شبكة فروع ونقاط بيع ماسبيرو للخدمات الرقمية والطباعة والاتصالات. تدير عمليات شحن وسحب المحافظ الإلكترونية (فودافون كاش، إنستاباي، فوري) وتسجيل كل معاملة لحظياً، مع دورة إقفال وتسليم الورديات بين الكاشيرات بمطابقة تامة للسيولة والأرصدة. تشمل حساب عمولات الموظفين وقواعد الحوافز التلقائية، خدمات الطباعة والإنترنت، نظام تذاكر داخلي للمتابعة والصيانة، ولوحة إشراف مركزية للمدير لمراقبة أداء كافة الفروع لحظياً.",
    logo: "/logos/maspero.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "roknalanaka",
    name: "ركن الأناقة",
    subtitle: "منظومة إدارة محلات الأزياء وورش تفصيل الستائر والمفروشات",
    desc: "منظومة إدارية شاملة تجمع بين مبيعات المحلات التجارية بالباركود وإدارة ورشة التفصيل والتصنيع المتخصصة في منصة واحدة متجانسة. تتابع مراحل طلبات العملاء من اختيار الأقمشة ورفع المقاسات إلى التصنيع بالورشة والتسليم النهائي. تدير حسابات الشركاء وتوزيع الأرباح الدورية والمصروفات المشتركة بدقة، مع إدارة كاملة للمخازن، المشتريات، الموردين، وإصدار التقارير المالية والتشغيلية لكل فرع وورشة.",
    logo: "/logos/roknalanaka.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "binqasim",
    name: "بي قاسم للاستيراد والتصدير",
    subtitle: "نظام إدارة عمليات الاستيراد وسلاسل الإمداد والتكلفة الفعلية",
    desc: "نظام تخطيط موارد متخصص في إدارة التجارة الدولية وعمليات الاستيراد والتوزيع لشركة بي قاسم. يتتبع شحنات الحاويات الجمركية من بلد المنشأ حتى الوصول للمستودعات، ويقوم بحساب التكلفة الفعلية (Landed Cost) بتوزيع مصاريف الشحن البحري، الرسوم الجمركية، النقل الداخلي، والتأمين على تكلفة كل صنف بدقة متناهية. يدير مستودعات التخزين المركزية، شبكة الموزعين، أسطول النقل، وشؤون الموظفين مع تقارير متقدمة للربحية والسيولة.",
    logo: "/logos/binqasim.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "opengym",
    name: "OpenGym",
    subtitle: "منصة إدارة الصالات والأندية الرياضية والاشتراكات السحابية",
    desc: "منصة سحابية متكاملة لإدارة الجيم والأندية الصحية، تدير باقات العضويات والاشتراكات وتجديدها وفترات التجميد والمدفوعات بدقة. تدعم تسجيل الحضور والانصراف السريع عبر الباركود أو البصمة/QR، وتعمل كتطبيق ويب تقدمي (PWA) يدعم العمل في وضع عدم الاتصال (Offline). تتضمن إدارة المدربين وحصص التدريب الخاص (PT) واحتساب العمولات، بوابة تفاعلية للمشتركين لمتابعة تقدمهم، ولوحة تحكم إدارية بتقارير الإيرادات والتنبيهات التلقائية.",
    logo: "/logos/opengym.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "riyadalquran",
    name: "جمعية رياض القرآن الكريم",
    subtitle: "منظومة إدارة المؤسسات الخيرية والمساعدات والحضانات التعليمية",
    desc: "منظومة إدارية ورقابية متكاملة لجمعية رياض القرآن الخيرية، تدير استقبال طلبات المساعدات وتصنيفها آلياً (الحالات المرضية، الأسر المتعففة، كفالات الأيتام، تجهيز العرائس، ترميم المنازل، والإطعام) ومتابعة دورة البحث الاجتماعي حتى الاعتماد والصرف. تشمل المنظومة إدارة الحضانة التعليمية بتسجيل الأطفال وبوابات خاصة لأولياء الأمور والمعلمين، وإدارة التبرعات والصناديق بكشوف حسابات شفافة وتقارير مالية تفصيلية.",
    logo: "/logos/riyadalquran.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "vos",
    name: "Volunteer Operating System",
    subtitle: "نظام إدارة الفرق التطوعية وتوثيق الشهادات بالـ QR كود",
    desc: "منصة سحابية متقدمة لإدارة العمل التطوعي والمنظمات غير الربحية: استقبال وفرز طلبات التطوع، تسكين المتطوعين في اللجان والفرق، وتنظيم الفعاليات والقوافل الميدانية مع تسجيل الحضور وساعات التطوع الموثقة. تتضمن نظاماً فريداً لإصدار الشهادات الإلكترونية المعتمدة والمزودة برمز QR للتحقق الفوري، ولوحات صدارة تفاعلية لتحفيز المتطوعين، وتقارير استبقاء دورية مع سجل تدقيق أمني شامل (Audit Trail) لكل إجراء.",
    logo: "/logos/vos.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "sash",
    name: "Sash — ساش",
    subtitle: "منظومة إدارة وتصنيع الأزياء الراقية والمفروشات والمشاغل",
    desc: "نظام سحابي راقٍ مخصص لدور الأزياء ومشاغل تفصيل المنسوجات والمفروشات الفاخرة. يدير دورة الطلبات الخاصة وكروت مقاسات العملاء وتفاصيل التصاميم، ومتابعة مراحل المشغل وورشة القص والتفصيل والتطريز والتشطيب النهائي. يشمل إدارة مخزون الأقمشة والحرير ومستلزمات الإنتاج، حسابات العملاء والدفعات المقدمة، ومتابعة العلامات التجارية المشتركة مع تقارير تشغيلية ولوحات ربحية لحظية للإدارة.",
    logo: "/logos/sash.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "almotawakel",
    name: "مؤسسة المتوكل",
    subtitle: "منظومة إدارة التجارة العامة وتوزيع البضائع والمستودعات",
    desc: "منظومة إدارية ومحاسبية متكاملة لمؤسسة المتوكل، تغطي دورة المبيعات والمشتريات وحركات التوريد للمخازن. تضبط أرصدة المستودعات المتعددة بحركات الجرد والتحويل المخزني الفوري، وتدير كشوف حسابات العملاء والموردين والشيكات وسندات القبض والصرف. تتيح رقابة دقيقة على حركة الخزينة والمصروفات اليومية مع استخراج القوائم المالية وتقارير الربحية اللحظية لمساعدة الإدارة في اتخاذ القرارات.",
    logo: "/logos/almotawakel.png",
    shots: [],
    youtubeId: "",
  },
];

export const FALLBACK_PROJECTS_EN = [
  {
    slug: "kishk",
    name: "Ahmed Kishk Institution",
    subtitle: "Curtains, Luxury Fabrics & Tailoring Management System",
    desc: "An end-to-end cloud ERP managing the full workflow across 4 branches: site visits and laser-accurate field measurements (tracks, fullness ratios, ceiling heights), quotation and contract signing, atelier cutting and sewing work orders, and final on-site installation with customer sign-off. Includes fabric roll and offcut inventory, customer accounts, sales invoicing, and granular branch permissions with live financial reports.",
    logo: "/logos/kishk.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "mazaya",
    name: "Mazaya Furniture",
    subtitle: "Modern Furniture Manufacturing & Showroom ERP System",
    desc: "An advanced ERP connecting furniture manufacturing lines and workshops with executive accounting. Manages production work orders (bedrooms, dining, salons, kitchens), precise sheet usage (MDF, counter, beech), and bill-of-materials costing (raw materials + labor + subcontractors + scrap). Features dedicated treasury drawers for factories and raw sheet trading, an integrated general journal, and branch transfer logs.",
    logo: "/logos/mazaya.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "elnazlawy",
    name: "Elnazlawy Showroom",
    subtitle: "Electrical Appliances & Home Lighting Distribution System",
    desc: "A comprehensive management suite for electrical appliance showrooms and mobile distribution fleets. Manages cash, installment, and credit sales, mobile van inventories with independent stock tracking per sales rep, and commercial bank cheque collection cycles. Delivers barcode inventory auditing, detailed vendor/customer ledgers, credit limit controls, and multi-drawer treasury monitoring.",
    logo: "/logos/elnazlawy.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "elhoot",
    name: "El Hoot Electrical Supplies",
    subtitle: "Wholesale Electrical Supplies & Cable Distribution ERP",
    desc: "A high-performance wholesale ERP built for electrical equipment, cables, and construction supplies. Handles bulk supply cycles, sales rep delivery routes, mobile vehicle stock, and on-field electronic billing. Features automated debt-aging schedules, credit-ceiling enforcement, inter-storehouse transfers, deferred cheque ledgers, and live liquidity dashboards.",
    logo: "/logos/elhoot.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "elnesr",
    name: "El Nesr Distribution",
    subtitle: "Fleet Distribution & Field Sales Rep Management System",
    desc: "A cloud-based distribution fleet platform uniting mobile warehouse stock, field invoicing, and HR payroll. Tracks vehicle delivery routes across governorates, reconciles daily sales rep cash floats and inventory in real time, and issues certified tax invoices with instant fast/slow-moving inventory analytics.",
    logo: "/logos/elnesr.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "rtx",
    name: "RTX Trade & Manufacturing",
    subtitle: "Industrial 3-Stage Manufacturing & Production Line ERP",
    desc: "An industrial ERP governing multi-tier production lines across three stages: 1) Raw material receipt and QC inspection, 2) Active manufacturing and assembly, 3) Finished goods packaging and dispatch. Features Bill of Materials (BOM), scrap rate calculation, stage-by-stage costing, and unified vendor/sales financial accounting.",
    logo: "/logos/rtx.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "maspero",
    name: "Maspero Digital Services",
    subtitle: "Multi-Branch Point of Sale (POS) & E-Wallet Management",
    desc: "A multi-branch POS network system managing digital services, printing centers, and telecom solutions. Processes instant top-ups and withdrawals across digital wallets (Vodafone Cash, InstaPay, Fawry) with strict cashier shift handover reconciliation. Features automated employee commission tiers, an internal IT ticketing queue, and executive real-time oversight.",
    logo: "/logos/maspero.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "roknalanaka",
    name: "Rokn Alanaqa",
    subtitle: "Fashion Retail Shops & Custom Upholstery Workshop ERP",
    desc: "An integrated platform combining barcode retail POS for garment stores with a specialized custom tailoring and curtain workshop. Tracks customer custom orders from fabric selection to tailoring and delivery, calculates partner profit distributions and shared expenses, and audits branch inventory and profitability.",
    logo: "/logos/roknalanaka.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "binqasim",
    name: "Bin Qasim Import & Export",
    subtitle: "International Trade, Container Logistics & Landed Cost ERP",
    desc: "A specialized supply chain ERP tracking import container shipments from origin ports to bonded warehouses. Calculates true Landed Cost by automatically distributing ocean freight, customs clearance duties, inland transit, and insurance across individual SKU costs. Manages distribution fleets, warehouse logistics, and net profit analytics.",
    logo: "/logos/binqasim.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "opengym",
    name: "OpenGym",
    subtitle: "Cloud Gym, Health Club & Membership Management Platform",
    desc: "A modern health club platform managing tiered memberships, auto-renewals, freeze periods, and payments. Supports rapid access check-in via barcode/biometrics, operates as an offline-first PWA, coordinates trainer private sessions (PT) with automated commission payouts, and delivers an interactive member portal.",
    logo: "/logos/opengym.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "riyadalquran",
    name: "Riyad Al-Quran Charity",
    subtitle: "Charitable Aid, Orphan Sponsorship & Nursery Management",
    desc: "A comprehensive social ERP managing charitable cases (medical, needy families, orphan sponsorships, house restoration, food packages) through home inspections and committee approvals. Features nursery student registration with parent and teacher portals, and transparent donor contribution ledgers.",
    logo: "/logos/riyadalquran.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "vos",
    name: "Volunteer Operating System",
    subtitle: "Volunteer Workforce & QR-Verified Digital Certificate System",
    desc: "A cloud platform for volunteer NGOs: onboarding and committee matching, convoy and event scheduling, and real-time volunteer hour tracking. Issues tamper-proof QR-verified digital certificates, provides gamified volunteer leaderboards, and logs a full security audit trail for every action.",
    logo: "/logos/vos.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "sash",
    name: "Sash Haute Couture",
    subtitle: "Luxury Fashion Atelier & Custom Textile Manufacturing ERP",
    desc: "An atelier ERP managing bespoke couture orders, client measurement cards, and workshop production stages (pattern cutting, stitching, embroidery, finishing). Manages imported silk and fabric stock, client prepayments, co-branded fashion lines, and real-time atelier margin reports.",
    logo: "/logos/sash.png",
    shots: [],
    youtubeId: "",
  },
  {
    slug: "almotawakel",
    name: "Almotawakel Trading",
    subtitle: "General Wholesale Trade, Warehouse & Logistics ERP",
    desc: "A robust ERP overseeing commercial supply, wholesale distribution, and multi-warehouse operations. Reconciles real-time stock balances across warehouses, automates customer and vendor debit/credit ledgers, and controls daily cash drawers and income statements.",
    logo: "/logos/almotawakel.png",
    shots: [],
    youtubeId: "",
  },
];
